Full-Stack-Capstone-Backend
bhushan354/Reservation-App-Backend pull request #16
Opened 2024-02-27 14:37 UTC by bhushan354

2024-02-27 15:15 UTC, bhushan354 commented
Hello air ,

if you found any bugs then please give a hint about how we can solve that particular error . it will be very helpful as we have very little time for project deadline .

Thank you !
Have a good day .

2024-02-27 15:16 UTC, bhushan354 commented
Hello Sir/Mam ,

if you found any bugs then please give a hint about how we can solve that particular error . it will be very helpful as we have very little time for project deadline .

Thank you !
Have a good day .

2024-02-27 16:56 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!










#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-02-27 16:56 UTC, Meltrust commented on config/database.yml
> +  database: booking_cap_db
- [ ] The testing database and the dev database have the same name, resulting on this:

![image](https://github.com/bhushan354/Full-Stack-Capstone-Backend/assets/57421823/a16ea70c-6ef4-40ad-8682-60dcfb5c0371)

Kindly, change the name of the testing database, so the name is different than the dev database.  You could use a name like `booking_cap_db_test`. 👍

2024-02-27 16:56 UTC, Meltrust commented on config/database.yml
> +  database: booking_cap_db
- [ ]  You are using rswag, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2024-02-27 16:56 UTC, Meltrust commented on README.md
> +  rails db:seed
- [ ] Before migrating and seeding the database, please include the command `rails db:create` so your users are able to create the database. 👍

2024-02-28 15:50 UTC, bhushan354 commented
Hello Dear reviewer, 
Now if you follow the README instructions carefully you will get a running app on your localmachine and still if you get stuck anywhere you can reach out to us on zoom or slack .

Thank you ,
Bhushan , Umair , Eugine .

2024-02-28 17:18 UTC, vichuge reviewed
Hi dear student, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2024-02-29 07:58 UTC, merged